# Preserve the build output of every successful build on Toolforge

name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout twinkle-enwiki
        uses: actions/checkout@v2

        # need to do this as long as we're relying on the latest twinkle-core rather than the npm packagee
      - name: Checkout twinkle-core
        uses: actions/checkout@v2
        with:
          repository: wikimedia-gadgets/twinkle-core
          path: '..'
      - run: cd ../twinkle-core && npm ci && cd -

      - run: npm ci
      - run: grunt build
      - name: Publish build output on Toolforge
        uses: garygrossgarten/github-action-scp@dba89d858413133b6e35da91a3c989cc8cde3ad4
        with:
          local: ${{github.workspace}}/build
          remote: /data/project/twinkle/public_html/enwiki/builds/${{github.sha}}
          host: login.toolforge.org
          username: ${{secrets.TOOLFORGE_USERNAME}}
          privateKey: ${{secrets.TOOLFORGE_PRIVATE_KEY}}
